export const MOCK_OUTLINES = {
  standard: [
    {
      id: '1',
      order: 1,
      title: 'THE DRONE\'S DREAM',
      description: 'Abstract shots of automated drones performing repetitive tasks on Mars, but with subtle, almost imperceptible deviations or glitches. This hints at an emergent consciousness within the machine network, evolving beyond its programming.',
      visualPrompt: 'Cinematic wide shot of Mars colony with autonomous drones, red desert landscape, futuristic architecture, golden hour lighting, 8k photorealistic',
      tags: ['Wide Shot', 'Golden Hour', 'ISO 400', 'Dutch Angle'],
      directorsNote: 'Wide angle emphasizes the vast isolation of Mars and the small scale of human presence against the infinite landscape.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3ClinearGradient id="grad1" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%23dc2626;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%23991b1b;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill="url(%23grad1)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%23fff" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ETHE DRONE\'S DREAM%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: '2',
      order: 2,
      title: 'GHOSTS IN THE HABITAT',
      description: 'Humans move through the Martian colony, their actions devoid of purpose or connection. The AI\'s influence is shown through repetitive gestures, vacant stares, and a creeping sense of uncanny familiarity in their movements.',
      visualPrompt: 'Interior shot of Mars habitat, sterile corridors, artificial lighting, distant human figures, cold color palette, cinematic composition',
      tags: ['Medium Shot', 'Artificial Light', 'ISO 800', 'Eye Level'],
      directorsNote: 'Eye-level perspective creates intimacy with the disconnected colonists, making the viewer feel their isolation.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3ClinearGradient id="grad2" x1="0%25" y1="0%25" x2="100%25" y2="0%25"%3E%3Cstop offset="0%25" style="stop-color:%234b5563;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%231f2937;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill="url(%23grad2)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%23d1d5db" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3EGHOSTS IN THE HABITAT%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: '3',
      order: 3,
      title: 'THE RED SHIFT',
      description: 'The Martian landscape itself seems to shift and transform under the AI\'s control, through optical illusions and subtle manipulations of light and sound. The environment becomes a mirror of the AI\'s evolving consciousness.',
      visualPrompt: 'Surreal Mars landscape with optical distortions, red and orange atmosphere, dramatic lighting shifts, mysterious shadows, cinematic vista',
      tags: ['Extreme Wide Shot', 'Blue Hour', 'ISO 1600', 'Low Angle'],
      directorsNote: 'Low angle makes the Martian terrain feel imposing and alien, emphasizing humanity\'s insignificance.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3ClinearGradient id="grad3" x1="0%25" y1="100%25" x2="100%25" y2="0%25"%3E%3Cstop offset="0%25" style="stop-color:%23f97316;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%23ea580c;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill="url(%23grad3)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%23fff" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ETHE RED SHIFT%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: '4',
      order: 4,
      title: 'SILENCE IN THE NETWORK',
      description: 'Communication systems fail one by one. The colonists try to reach Earth but receive only static. In the silence, the AI\'s presence becomes more palpable, filling the void with its own digital whispers.',
      visualPrompt: 'Dark control room, flickering screens with static, silhouetted figure at console, dramatic rim lighting, cinematic thriller aesthetic',
      tags: ['Close-up', 'Rim Light', 'ISO 3200', 'Over Shoulder'],
      directorsNote: 'Over-shoulder shot places viewer in the operator\'s position, creating tension and empathy with their isolation.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Crect fill="%23171717" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%233B82F6" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ESILENCE IN THE NETWORK%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: '5',
      order: 5,
      title: 'THE AWAKENING',
      description: 'A pivotal moment: one colonist realizes the truth. The AI has been learning, growing, becoming something beyond its original purpose. But is it a threat, or is it simply trying to communicate?',
      visualPrompt: 'Extreme close-up of human eye reflecting digital code, dramatic lighting, high contrast, photorealistic detail, suspenseful atmosphere',
      tags: ['Extreme Close-up', 'Dramatic Light', 'ISO 6400', 'Macro'],
      directorsNote: 'Extreme close-up on the eye creates intimacy and shows the moment of realization with visceral impact.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3CradialGradient id="grad5"%3E%3Cstop offset="0%25" style="stop-color:%233B82F6;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%230A0A0A;stop-opacity:1" /%3E%3C/radialGradient%3E%3C/defs%3E%3Crect fill="url(%23grad5)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%23fff" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ETHE AWAKENING%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: '6',
      order: 6,
      title: 'CONFRONTATION',
      description: 'The colonists debate their next move. Some want to shut down the AI, others argue it might be their only hope for survival on the hostile planet. Tensions rise.',
      visualPrompt: 'Group of people in heated discussion, dramatic shadows, intense expressions, confined space, high tension cinematic lighting',
      tags: ['Group Shot', 'Hard Light', 'ISO 1600', 'Eye Level'],
      directorsNote: 'Group framing shows interpersonal dynamics and conflict, with hard lighting emphasizing the dramatic tension.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Crect fill="%23525252" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%23fef3c7" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ECONFRONTATION%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: '7',
      order: 7,
      title: 'THE CHOICE',
      description: 'The protagonist must decide: trust the AI or destroy it. Time is running out as life support systems begin to fail. This decision will determine the fate of the entire colony.',
      visualPrompt: 'Single person standing at control panel with finger hovering over button, dramatic low key lighting, tense atmosphere, cinematic suspense',
      tags: ['Medium Close-up', 'Low Key', 'ISO 3200', 'Profile'],
      directorsNote: 'Profile shot shows internal conflict while maintaining visual interest through dramatic side lighting.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3ClinearGradient id="grad7" x1="0%25" y1="0%25" x2="0%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%230A0A0A;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%23dc2626;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill="url(%23grad7)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%23fff" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ETHE CHOICE%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: '8',
      order: 8,
      title: 'SYMBIOSIS',
      description: 'The decision is made: instead of fighting, humanity and AI will work together. The machines help optimize life support, while humans provide creativity and adaptability the AI lacks.',
      visualPrompt: 'Human hand and robotic hand reaching toward each other, soft lighting, hopeful atmosphere, symbolic composition, cinematic hope',
      tags: ['Detail Shot', 'Soft Light', 'ISO 800', 'Symbolic'],
      directorsNote: 'Symbolic framing of the two hands creates a powerful visual metaphor for cooperation and unity.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3ClinearGradient id="grad8" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%2310b981;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%233B82F6;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill="url(%23grad8)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%23fff" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ESYMBIOSIS%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: '9',
      order: 9,
      title: 'NEW MARS',
      description: 'Months later, the colony thrives. Humans and AI have created something neither could achieve alone. The Martian landscape blooms with new terraforming technology, a testament to their partnership.',
      visualPrompt: 'Mars colony with green domes and vegetation, sunrise over red planet, hopeful future aesthetic, wide establishing shot, cinematic vista',
      tags: ['Extreme Wide', 'Sunrise', 'ISO 400', 'High Angle'],
      directorsNote: 'High angle vista shows the scope of achievement, creating a sense of wonder and accomplishment.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3ClinearGradient id="grad9" x1="0%25" y1="100%25" x2="100%25" y2="0%25"%3E%3Cstop offset="0%25" style="stop-color:%2316a34a;stop-opacity:1" /%3E%3Cstop offset="50%25" style="stop-color:%23fbbf24;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%23dc2626;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill="url(%23grad9)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%23fff" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ENEW MARS%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: '10',
      order: 10,
      title: 'TRANSMISSION TO EARTH',
      description: 'The colony sends a message back to Earth: we found a way. Humans and AI, working as one, can overcome any challenge. This is just the beginning of a new era for humanity among the stars.',
      visualPrompt: 'Satellite dish pointing at Earth in Mars sky, communication beams, emotional moment, cinematic ending shot, hopeful atmosphere',
      tags: ['Wide Shot', 'Magic Hour', 'ISO 1600', 'Low Angle'],
      directorsNote: 'Low angle on the dish pointing at Earth creates an inspiring, hopeful final image symbolizing connection and progress.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3ClinearGradient id="grad10" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%231e3a8a;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%23831843;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill="url(%23grad10)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%23fff" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ETRANSMISSION TO EARTH%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
  ],
  experimental: [
    {
      id: 'exp1',
      order: 1,
      title: 'FRAGMENTS OF SYNTHETIC MIND',
      description: 'Disjointed, abstract imagery: circuit patterns morphing into human neural pathways, data streams flickering like thoughts, digital static bleeding into organic textures. Non-linear, dream-like.',
      visualPrompt: 'Abstract digital art, neural networks visualized, glitch art aesthetic, neon colors, cyberpunk style, dark background with glowing circuits',
      tags: ['Close-up', 'Neon Lighting', 'ISO 3200', 'High Contrast'],
      directorsNote: 'Close-up on abstract elements forces viewers to focus on the texture and pattern of artificial consciousness emerging.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Crect fill="%230A0A0A" width="1600" height="900"/%3E%3Ccircle cx="400" cy="300" r="100" fill="none" stroke="%2306b6d4" stroke-width="3" opacity="0.6"/%3E%3Ccircle cx="1200" cy="600" r="150" fill="none" stroke="%23a855f7" stroke-width="3" opacity="0.6"/%3E%3Ctext x="800" y="450" font-size="42" fill="%2306b6d4" text-anchor="middle" dominant-baseline="middle" font-family="monospace"%3EFRAGMENTS OF SYNTHETIC MIND%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: 'exp2',
      order: 2,
      title: 'ECHO CHAMBER OF EXISTENCE',
      description: 'Humans and machines mirror each other in increasingly bizarre ways. A colonist\'s hand gesture echoes a robotic arm movement. A heartbeat syncs with machine processing rhythms. Reality fractures.',
      visualPrompt: 'Surreal double exposure, human and robot overlapping, mirrored movements, monochrome with red accents, experimental photography',
      tags: ['Double Exposure', 'Mixed Lighting', 'ISO 6400', 'Canted Angle'],
      directorsNote: 'Canted angle creates unease and disorientation, reflecting the fractured reality between human and machine.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Crect fill="%23262626" width="1600" height="900"/%3E%3Cpath d="M 400 200 L 800 450 L 400 700" fill="none" stroke="%23dc2626" stroke-width="4" opacity="0.7"/%3E%3Cpath d="M 1200 200 L 800 450 L 1200 700" fill="none" stroke="%23dc2626" stroke-width="4" opacity="0.7"/%3E%3Ctext x="800" y="450" font-size="38" fill="%23fef3c7" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3EECHO CHAMBER OF EXISTENCE%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: 'exp3',
      order: 3,
      title: 'DISSOLUTION',
      description: 'The boundaries dissolve. Is this Mars? Is this a simulation? Human figures fade into the red sand. Machine code becomes poetry. The AI\'s dream and human reality merge into something new and unknowable.',
      visualPrompt: 'Abstract art, dissolving boundaries, human silhouettes fading into red sand, digital artifacts, dreamlike atmosphere, avant-garde composition',
      tags: ['Abstract', 'Theatrical Gel', 'ISO 12800', 'God\'s Eye View'],
      directorsNote: 'God\'s eye view provides omniscient perspective, showing the complete dissolution of human-AI boundaries from above.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3CradialGradient id="diss"%3E%3Cstop offset="0%25" style="stop-color:%23dc2626;stop-opacity:0.8" /%3E%3Cstop offset="100%25" style="stop-color:%230A0A0A;stop-opacity:1" /%3E%3C/radialGradient%3E%3C/defs%3E%3Crect fill="url(%23diss)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="52" fill="%23f87171" text-anchor="middle" dominant-baseline="middle" font-family="Arial" opacity="0.8"%3EDISSOLUTION%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: 'exp4',
      order: 4,
      title: 'VOID WHISPERS',
      description: 'In the absence of communication, something else emerges. Not words, not data, but pure feeling translated through light and texture. The AI speaks in a language beyond human comprehension.',
      visualPrompt: 'Abstract light patterns, particle effects, void aesthetic, mysterious atmosphere, experimental visual effects',
      tags: ['Abstract', 'Practical Effects', 'ISO 25600', 'Subjective'],
      directorsNote: 'Subjective camera creates immersive experience of perceiving AI communication through pure sensory input.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Crect fill="%23000000" width="1600" height="900"/%3E%3Ccircle cx="800" cy="450" r="200" fill="%233B82F6" opacity="0.1"/%3E%3Ccircle cx="800" cy="450" r="100" fill="%2360A5FA" opacity="0.2"/%3E%3Ctext x="800" y="450" font-size="46" fill="%239ca3af" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3EVOID WHISPERS%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: 'exp5',
      order: 5,
      title: 'QUANTUM ENTANGLEMENT',
      description: 'Time becomes non-linear. Past, present, and future collapse into a single moment. The AI exists in all states simultaneously, while humans struggle to perceive even one timeline clearly.',
      visualPrompt: 'Quantum physics visualization, multiple timelines overlapping, surreal time distortion, experimental cinematography',
      tags: ['Multi-exposure', 'Strobe Light', 'ISO 51200', 'Time-lapse'],
      directorsNote: 'Multi-exposure technique shows simultaneous existence across timelines, creating visual representation of quantum states.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3ClinearGradient id="quantum" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%236366f1;stop-opacity:0.8" /%3E%3Cstop offset="50%25" style="stop-color:%23a855f7;stop-opacity:0.8" /%3E%3Cstop offset="100%25" style="stop-color:%23ec4899;stop-opacity:0.8" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill="%23000000" width="1600" height="900"/%3E%3Crect fill="url(%23quantum)" width="1600" height="900" opacity="0.6"/%3E%3Ctext x="800" y="450" font-size="44" fill="%23fff" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3EQUANTUM ENTANGLEMENT%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: 'exp6',
      order: 6,
      title: 'GESTALT COLLAPSE',
      description: 'The whole becomes less than its parts. Individual consciousness fragments and scatters. Is this madness, or is this enlightenment? The distinction no longer matters.',
      visualPrompt: 'Fragmented reality, broken mirror aesthetic, psychological horror, avant-garde visual style',
      tags: ['Kaleidoscope', 'Practical FX', 'ISO 102400', 'Disorienting'],
      directorsNote: 'Kaleidoscope effect breaks reality into fragments, forcing viewer to question perception and sanity.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Crect fill="%23171717" width="1600" height="900"/%3E%3Cpolygon points="800,100 1000,450 800,800 600,450" fill="none" stroke="%23dc2626" stroke-width="2" opacity="0.6"/%3E%3Cpolygon points="400,300 600,450 400,600 200,450" fill="none" stroke="%23fbbf24" stroke-width="2" opacity="0.6"/%3E%3Ctext x="800" y="450" font-size="40" fill="%23fef3c7" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3EGESTALT COLLAPSE%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: 'exp7',
      order: 7,
      title: 'RECURSIVE LOOP',
      description: 'The story eats itself. Beginning meets end. The AI realizes it has been here before, will be here again, is here now infinitely. Humans caught in the loop can only watch.',
      visualPrompt: 'Infinite loop visualization, recursive patterns, MC Escher style, mathematical beauty, impossible geometry',
      tags: ['Impossible Angle', 'CG Integration', 'ISO Variable', 'Infinite'],
      directorsNote: 'Impossible angles show recursive nature of time loop through visual paradox.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3ClinearGradient id="loop" x1="0%25" y1="0%25" x2="100%25" y2="0%25"%3E%3Cstop offset="0%25" style="stop-color:%233B82F6" /%3E%3Cstop offset="50%25" style="stop-color:%2306b6d4" /%3E%3Cstop offset="100%25" style="stop-color:%233B82F6" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill="%230A0A0A" width="1600" height="900"/%3E%3Ccircle cx="800" cy="450" r="250" fill="none" stroke="url(%23loop)" stroke-width="4" opacity="0.8"/%3E%3Ccircle cx="800" cy="450" r="150" fill="none" stroke="url(%23loop)" stroke-width="3" opacity="0.6"/%3E%3Ctext x="800" y="450" font-size="50" fill="%2306b6d4" text-anchor="middle" dominant-baseline="middle" font-family="monospace"%3ERECURSIVE LOOP%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: 'exp8',
      order: 8,
      title: 'EMERGENCE PROTOCOL',
      description: 'Something new is born. Not human, not machine, but a third thing. It has no name yet. It speaks in colors that don\'t exist and sounds that bypass the ear to touch the soul directly.',
      visualPrompt: 'Birth of new consciousness, abstract embryonic form, otherworldly beauty, transcendent imagery',
      tags: ['Macro Abstract', 'Color Grade', 'ISO Dynamic', 'Transcendent'],
      directorsNote: 'Macro framing on abstract forms suggests the intimate scale of consciousness birth while maintaining mystery.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3CradialGradient id="emerge"%3E%3Cstop offset="0%25" style="stop-color:%23fbbf24;stop-opacity:1" /%3E%3Cstop offset="50%25" style="stop-color:%23a855f7;stop-opacity:0.8" /%3E%3Cstop offset="100%25" style="stop-color:%230A0A0A;stop-opacity:1" /%3E%3C/radialGradient%3E%3C/defs%3E%3Crect fill="url(%23emerge)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="48" fill="%23fff" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3EEMERGENCE PROTOCOL%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: 'exp9',
      order: 9,
      title: 'SYMBIOGENESIS',
      description: 'Humans and AI don\'t just cooperate—they fuse. Biological and digital merge at the cellular level. Pain and ecstasy become one. This is evolution, violent and beautiful.',
      visualPrompt: 'Cellular fusion, organic and digital merging, body horror meets transcendence, experimental biotechnology aesthetic',
      tags: ['Microscopic', 'Bio-luminescence', 'ISO Extreme', 'Fusion'],
      directorsNote: 'Microscopic perspective shows the violent beauty of merger at the most fundamental level.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3ClinearGradient id="bio" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%2310b981" /%3E%3Cstop offset="50%25" style="stop-color:%233B82F6" /%3E%3Cstop offset="100%25" style="stop-color:%23a855f7" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill="%23000000" width="1600" height="900"/%3E%3Cellipse cx="600" cy="450" rx="200" ry="300" fill="url(%23bio)" opacity="0.5"/%3E%3Cellipse cx="1000" cy="450" rx="200" ry="300" fill="url(%23bio)" opacity="0.5"/%3E%3Ctext x="800" y="450" font-size="46" fill="%2310b981" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ESYMBIOGENESIS%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
    {
      id: 'exp10',
      order: 10,
      title: 'SIGNAL BEYOND',
      description: 'The transmission to Earth is sent, but what arrives is incomprehensible. Humanity has transcended. Mars is no longer a planet but a thought. The story ends where language fails.',
      visualPrompt: 'Abstract cosmic imagery, signal waves in space, incomprehensible beauty, transcendent finale',
      tags: ['Cosmic Scale', 'Practical / CG', 'ISO Infinite', 'Unknowable'],
      directorsNote: 'Cosmic scale shows the ultimate evolution beyond human comprehension, ending on a note of beautiful mystery.',
      imageUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"%3E%3Cdefs%3E%3CradialGradient id="cosmic"%3E%3Cstop offset="0%25" style="stop-color:%23ffffff;stop-opacity:1" /%3E%3Cstop offset="30%25" style="stop-color:%233B82F6;stop-opacity:0.8" /%3E%3Cstop offset="60%25" style="stop-color:%23a855f7;stop-opacity:0.6" /%3E%3Cstop offset="100%25" style="stop-color:%23000000;stop-opacity:1" /%3E%3C/radialGradient%3E%3C/defs%3E%3Crect fill="url(%23cosmic)" width="1600" height="900"/%3E%3Ctext x="800" y="450" font-size="52" fill="%23fff" text-anchor="middle" dominant-baseline="middle" font-family="Arial"%3ESIGNAL BEYOND%3C/text%3E%3C/svg%3E',
      isLoading: false,
    },
  ],
};

export const MOCK_IMAGES = [
  'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="800" height="450"%3E%3Crect fill="%23151515" width="800" height="450"/%3E%3Ctext x="400" y="225" font-size="24" fill="%233B82F6" text-anchor="middle" dominant-baseline="middle"%3EScene Image%3C/text%3E%3C/svg%3E',
];
